### ISSUE TITLE
CLI question

### ISSUE THREAD

**Issue by cjlm** [cjlm/send-to-workflowy#4]
I forgot to enable Issues on the repo so @markfirmware opened a PR with a question instead...

> Does this include a cli that I can use to fetch wf data? If so, how is it installed and run?
> opusfluxus is not working for me - keeps asking for my email.

Yes, there is a CLI although I haven't documented it as it's not fully tested. I also found that opusfluxus wasn't working but I'm not clear how it's different from `send-to-workflowy` now. The CLI should work if you do the following in the base directory:

```
yarn
node wf-cli
```
It uses the same logic as opusfluxus to save your credentials to a file in your $HOME

Please note that I'll be moving it into it's own yarn workspace in the next release. It shouldn't be in the base directory like it is now.

Let me know how you get on @markfirmware!

**Comment by markfirmware** [comment]
Thanks! I used gitpod to try it (you will need to approve gitpod access to your github account)

    https://gitpod.io/#https://github.com/cjlm/send-to-workflowy

Then I did

    yarn

When that was done I, did

    gitpod /workspace/send-to-workflowy $ node wf-cli tree 1
    ⦿ fetching workflowy tree
    No config detected... starting authentication process...
    What is your workflowy login info? This will not be saved, merely used once to authenticate.
    ? Email: › (node:1135) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of null
    at Object.parseCookies (/workspace/send-to-workflowy/utils.js:5:10)
    at WorkflowyClient.login (/workspace/send-to-workflowy/index.js:68:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async WorkflowyClient.refresh (/workspace/send-to-workflowy/index.js:101:7)
    at async initialize (/workspace/send-to-workflowy/wf-cli.js:24:3)
    at async Command.<anonymous> (/workspace/send-to-workflowy/wf-cli.js:93:16)
    at async Command.parseAsync (/workspace/send-to-workflowy/node_modules/commander/lib/command.js:871:5)
    (Use `node --trace-warnings ...` to show where the warning was created)
    (node:1135) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
    (node:1135) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by markfirmware** [comment]
Actually, ignoring that error and entering my email, I get:

    Login successful.
    Failed to write sessionid to config

**Comment by cjlm** [comment]
Hmm, strange. I'll look into it.

What auth do you use with WF? Password? Multifactor? Email code?

**Comment by cjlm** [comment]
Looks like it's working correctly but is unable to save to HOME when using GitPod.

The initial error needs fixing though

**Comment by cjlm** [comment]
I'm not sure about the gitpod config bit but there was a pretty obvious mistake in the auth code. I've fixed it on the `cli-fix` branch for a future merge

**Comment by markfirmware** [comment]
Thanks! I just tried fix-cli and got

    What is your workflowy login info? This will not be saved, merely used once to authenticate.
    ✔ Email: … mkendrat@yahoo.com
    err TypeError: Cannot read property 'split' of null
    at Object.parseCookies (/workspace/send-to-workflowy/utils.js:5:10)
    at WorkflowyClient.login (/workspace/send-to-workflowy/index.js:68:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async auth (/workspace/send-to-workflowy/wf-cli.js:217:5)
    at async initialize (/workspace/send-to-workflowy/wf-cli.js:17:5)
    at async Command.<anonymous> (/workspace/send-to-workflowy/wf-cli.js:93:16)
    at async Command.parseAsync (/workspace/send-to-workflowy/node_modules/commander/lib/command.js:871:5)
    Login successful.

Since I only entered my email and not any password or the like, I think the successful message is not accurate

**Comment by markfirmware** [comment]
Thanks! I tried fix-cli:

    What is your workflowy login info? This will not be saved, merely used once to authenticate.
    ✔ Email: …  #xxx@xxx
    err TypeError: Cannot read property 'split' of null
    at Object.parseCookies (/workspace/send-to-workflowy/utils.js:5:10)
    at WorkflowyClient.login (/workspace/send-to-workflowy/index.js:68:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async auth (/workspace/send-to-workflowy/wf-cli.js:217:5)
    at async initialize (/workspace/send-to-workflowy/wf-cli.js:17:5)
    at async Command.<anonymous> (/workspace/send-to-workflowy/wf-cli.js:93:16)
    at async Command.parseAsync (/workspace/send-to-workflowy/node_modules/commander/lib/command.js:871:5)
    Login successful.

Since I only entered my email and not a password or the like, I think the successful message is not accurate.

**Comment by cjlm** [comment]
Argh. I've pushed a fix for the cookies thing too. It may work now but it's clear the error handling needs an overhaul.

**Comment by cjlm** [comment]
That appears to resolve it for me on gitpod:

```
gitpod /workspace/send-to-workflowy $ node wf-cli tree 1
⦿ fetching workflowy tree
No config detected... starting authentication process...
What is your workflowy login info? This will not be saved, merely used once to authenticate.
✔ Email: … <email>
✔ Password … ********************************************************
Login successful.
Your session id is: <sessionid>
Successfully wrote sessionid to /home/gitpod/.config/send-to-workflowy-nodejs/config.json
```

**Comment by markfirmware** [comment]
I am still having trouble on gitpod. I will add a report later tonight.

**Comment by cjlm** [comment]
Any update @markfirmware?
